name: yoruba_tts
description: "Flutter package to generate speech from text using the Meta's mms-tts-yor model on HuggingFace API"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0